# Generated by Django 6.0.5 on 2026-05-16 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class (e.g. bi-wifi)",
                        max_length=50,
                        verbose_name="Icon class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "image",
                    models.ImageField(upload_to="destinations/", verbose_name="Image"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                ("address", models.CharField(max_length=300, verbose_name="Address")),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="District / Neighbourhood",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price per night"
                    ),
                ),
                ("max_guests", models.PositiveIntegerField(verbose_name="Max guests")),
                ("bedrooms", models.PositiveIntegerField(verbose_name="Bedrooms")),
                ("bathrooms", models.PositiveIntegerField(verbose_name="Bathrooms")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("all", "All properties"),
                            ("collection", "The Collection*"),
                            ("casa_wynwood", "Casa Wynwood"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, to="properties.amenity", verbose_name="Amenities"
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="properties.destination",
                        verbose_name="Destination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="properties/", verbose_name="Image"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt text"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property image",
                "verbose_name_plural": "Property images",
                "ordering": ["order"],
            },
        ),
    ]
