# Generated by Django 6.0.5 on 2026-05-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(blank=True, upload_to='additional_services/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Additional Service',
                'verbose_name_plural': 'Additional Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Discount code'),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='bookings.additionalservice', verbose_name='Additional services'),
        ),
    ]
