# Generated by Django 6.0.5 on 2026-05-16 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "Booking confirmed"),
                            ("booking_cancelled", "Booking cancelled"),
                            ("booking_pending", "Booking pending"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sent at"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-sent_at"],
            },
        ),
    ]
